name: Linting

on:
  push:
    branches:
      - "*"
    paths:
      - '**.js*'
      - '**.ts*'
      - 'package*.json'
      - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - "main"
    paths:
      - '**.js*'
      - '**.ts*'
      - 'package*.json'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # ESLint and Prettier must be in  `package.json`
      - run: yarn install --frozen-lockfile
        env:
          NODE_ENV: development
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          auto_fix: true
          eslint: true
          prettier: false
